[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"

[font]
normal.family = "Hack Nerd Font"
size = 13

[cursor]
style.blinking = "Always"
blink_interval = 500

[colors]
cursor.background = "#c015ef"
cursor.foreground = "#ffffff"

[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.normal]
black = '0x282828'
red = '0xcc241d'
green = '0x98971a'
yellow = '0xd79921'
blue = '0x458588'
magenta = '0xb16286'
cyan = '0x689d6a'
white = '0xa89984'

[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Option", chars = "\u001bb" },    # Jump left a word
  { key = "ArrowRight", mods = "Option", chars = "\u001bf" },   # Jump right a word 
  { key = "ArrowLeft", mods = "Command", chars = "\u001bOH" },  # Start of line
  { key = "ArrowRight", mods = "Command", chars = "\u001bOF" }, # End of line 
  { key = "Backspace", mods = "Command", chars = "\u0015" },    # delete word/line
]
